name: Borsa Robotu

on:
  schedule:
    # 07:30, 16:00 ve 22:00 (Türkiye Saati)
    - cron: '30 4 * * *'
    - cron: '0 13 * * *'
    - cron: '0 19 * * *'
  workflow_dispatch:

jobs:
  calistir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Kütüphaneleri Yükle
        run: pip install pandas numpy yfinance scikit-learn
      - name: Analizi Başlat
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
          ALICI_MAIL: ${{ secrets.ALICI_MAIL }}
        run: python main.py
